# Example setup options that may be overlaid during setup
# using the --optionsFile option. Run `setup --help` for further
# instructions.
core:
  Authentication.Protocol: "oidc"
  Authentication.oidcClientId: "papclient"
  Authentication.redirectUri: "https://sripaz-pingauthorizepap.ping-devops.com/idp-callback"
  Authentication.scope: "openid email profile"
  # Use a JWT claim other than "sub" for the OIDC User ID. 
  #
  #  Authentication.oidcUserIdField: jwt_claim
  #
  # Cache the OIDC JWKS response with an expiry period (in seconds). A value of
  # `-1` will cause the Policy Editor to cache the JWKS endpoint
  # response indefinitely (the default). Use a value of `0` to disable
  # JWKS endpoint caching.
  #
  # Note that regardless of the configured value,
  # the application will continue to request
  # the JWKS endpoint whenever it encounters a `kid` that is not present
  # in the cached response.
  #
  # The JWKS endpoint is provided either directly, through the
  # `authWellKnownEndpoints` configuration option
  # (see the `ui` section), or indirectly, by specifying the
  # OIDC configuration endpoint through the
  # `PING_OIDC_CONFIGURATION_ENDPOINT` environment variable.
  #
  # This option only affects server-side behavior.
  #
  #  Authentication.oidcJwksCacheExpirySeconds: -1
  #
  # Add policy configuration keys here. The value for a policy 
  # configuration key may be provided via an environment variable 
  # using the notation '${environment-variable}'.
  #
  #  PolicyConfigurationKeyName: PolicyConfigurationKeyValue
keystores:
  # Define key stores used by policy information providers here.
  #
  #  - name: CustomKeyStore
  #    resource: /path/to/custom-keystore.jks
  #    password: keystore-password
truststores:
  # Define trust stores used by policy information providers here.
  #
  #  - name: CustomTrustStore
  #    resource: /path/to/custom-truststore.jks
  #    password: truststore-password
deploymentPackageData:
  # Define a key store to use for signing deployment packages here.
  #
  #  contentType: json
  #  keystore:
  #    resource: /path/to/deployment-package-signing-keystore.jks
  #    password: keystore-password
  #  securityLevel: signed
  #  signingKey:
  #    alias: signing-cert-alias
  #    password: private-key-password
deploymentPackageStores:
  # Define deployment package store publishing targets here.
  #
  # - name: Filesystem store
  #   description: File system directory store
  #   type: filesystem
  #   path: /path/to/deployment-package-store/
  # - name: Signed filesystem store
  #   description: Signed file system directory store
  #   type: filesystem
  #   path: /path/to/signed-deployment-package-store/
  #   securityLevel: signed
  #   keystore:
  #     resource: /path/to/deployment-package-signing-keystore.jks
  #     password: keystore-password
  #   signingKey:
  #     alias: signing-cert-alias
  #     password: private-key-password
  - name: S3 bucket store
    description: AWS S3 bucket store
    type: s3bucket
    securityLevel: unsigned
    config:
      bucket: store-bucket-name
      prefix: store-prefix
      endpoint: https://s3.amazonaws.com
      region: us-east-2
      accessKey: aws-access-key
      secretKey: aws-secret-key
  #
  # - name: Azure blob storage store
  #   description: Microsoft Azure blob storage store
  #   type: azure
  #   securityLevel: unsigned
  #   config:
  #     connection-string: DefaultEndpointsProtocol=[http|https];AccountName=myAccountName;AccountKey=myAccountKey
  #     container: azure-blob-storage-container-name
  #     prefix: azure-blob-storage-prefix
  #
securityHeaders:
  # Configure the values that the Policy Editor will set in its
  # responses for the X-Frame-Options, Content-Security-Policy, and/or
  # Access-Control-Allow-Origin HTTP security headers here.
  #
  # X-Frame-Options: "deny"
  # Content-Security-Policy: "default-src https:"
  # Access-Control-Allow-Origin: "*"
ui:
  # Individually configure the OpenID Connect endpoints. This only applies when configuring the Policy Editor
  # to use OpenID Connect for authentication.
  # 
  authType: "oidc"
  authClientConfig:
    authWellKnownEndpoints:
      issuer: https://${PING_PF_ISSUER}
      authorizationEndpoint: https://${PING_PF_ISSUER}/as/authorization.oauth2
      jwksUri: https://${PING_PF_ISSUER}/pf/JWKS
      tokenEndpoint: https://${PING_PF_ISSUER}/as/token.oauth2
      userinfoEndpoint: https://${PING_PF_ISSUER}/idp/userinfo.openid
      endSessionEndpoint: https://${PING_PF_ISSUER}/idp/startSLO.ping
      introspectionEndpoint: https://${PING_PF_ISSUER}/as/introspect.oauth2
cache:
  # Configure an external attribute cache for use in the Trust Framework. Note that these configuration options
  # only apply to the Policy Editor and do not get exported with a deployment package. This means that to use
  # the same cache for PingAuthorize running in embedded PDP mode, you must configure equivalent settings
  # either through the Administrative Console or dsconfig.
  #
  # The "cacheConfig" sections below are examples of each external attribute caching mode. The "username"
  # and "password" fields are only required when the external Redis instance has AUTH enabled.
  # Customers using older Redis instances and the "requirepass" configuration only need to set "password".
  #
  # To use a Redis-based instance for any cache-enabled Trust Framework attributes, uncomment the
  # "provider" property below, along with an appropriately modified "cacheConfig" section.
  #
  # provider: redis
  #
  # Example cacheConfig - Single Redis instance
  #
  # cacheConfig:
  #   mode: single_instance
  #   nodeAddresses: redis://localhost:6379
  #   username: <optional>
  #   password: <optional>
  #
  # Example cacheConfig - Single Redis instance using TLS
  #
  # cacheConfig:
  #   mode: single_instance
  #   nodeAddresses: rediss://localhost:6379
  #   username: <optional>
  #   password: <optional>
  #
  # Example cacheConfig - Replicated Redis
  #
  # cacheConfig:
  #   mode: replicated
  #   nodeAddresses: redis://example.com:6379,redis://example.com:6380
  #   username: <optional>
  #   password: <optional>
  #
  # Example cacheConfig - Redis Sentinel
  #
  # cacheConfig:
  #   mode: sentinel
  #   nodeAddresses: redis://example.com:23679,redis://example.com:23680,redis://example.com:23681
  #   masterName: mymaster
  #   database: 0
  #   scanInterval: 1000
  #   checkSentinelList: false
  #   username: <optional>
  #   password: <optional>
  #
  # Example cacheConfig - ElastiCache
  #
  # cacheConfig:
  #   mode: elasticache
  #   replicationGroupId: my-replication-group-id
  #   username: <optional>
  #   password: <optional>
logging:
  level: INFO
  loggers:
    "DataNucleus": ERROR
    "DataNucleus.Enhancer": "OFF"
    "org.glassfish.jersey.internal.Errors": ERROR
    "com.symphonicsoft.policyanalysis.PolicyTranslator": ERROR
    # If instructed to do so by Ping Identity Support, you can enable
    # additional logging for HTTP errors by uncommenting one of the following
    # lines and running setup. This will cause stack trace details about HTTP
    # errors to be recorded to logs/debug.log.
    #
    # To enable additional logging for HTTP 50x errors only:
    # "com.symphonicsoft.rest.BaseExceptionMapper": ERROR
    #
    # To enable additional logging for HTTP 40x and 50x errors:
    # "com.symphonicsoft.rest.BaseExceptionMapper": DEBUG
    "DECISION_AUDIT_LOG":
      level: INFO
      additive: false
      appenders:
        - type: file
          currentLogFilename: logs/decision-audit.log
          archive: true
          maxFileSize: 250MB
          archivedLogFilenamePattern: logs/decision-audit.%i.log.gz
          archivedFileCount: 10
          logFormat: "[%date{ISO8601}] %msg%n"
    "ADMIN_POINT_AUDIT":
      level: INFO
      additive: false
      appenders:
        - type: file
          currentLogFilename: logs/management-audit.log
          archive: false
          archivedLogFilenamePattern: logs/management-audit.%i.log.gz
          archivedFileCount: 10
          logFormat: "[%date{ISO8601}] %msg%n"
    metrics:
      additive: false
      appenders:
        - type: file
          currentLogFilename: logs/metrics.log
          maxFileSize: 250MB
          archive: true
          archivedLogFilenamePattern: logs/metrics.%i.log.gz
          archivedFileCount: 10
          logFormat: "logger=metrics, timestamp=%date{yyyyMMdd'T'HHmmss.SSS}, %msg%n"
  appenders:
    - type: console
      threshold: INFO
      target: stdout
      logFormat: "%-5level [%date{ISO8601}] %c: %msg%n"
    - type: file
      threshold: DEBUG
      currentLogFilename: logs/debug.log
      maxFileSize: 250MB
      archive: true
      archivedLogFilenamePattern: logs/debug.%i.log.gz
      archivedFileCount: 10
      logFormat: "%-5level [%date{ISO8601}] [%thread] %c: %msg%n"
    - type: file
      threshold: INFO
      currentLogFilename: logs/authorize-pe.log
      maxFileSize: 250MB
      archive: true
      archivedLogFilenamePattern: logs/authorize-pe.%i.log.gz
      archivedFileCount: 10
      logFormat: "%-5level [%date{ISO8601}] %c: %msg%n"
